import { Footer } from '@/components/layout/Footer';
import { Header } from '@/components/layout/Header';
import { Providers } from '@/providers/Providers';
import '@/app/globals.css';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<Providers>
			<html lang='en'>
				<body
					className='min-h-screen flex flex-col'
					data-testid='root-layout-wrapper'>
					<Header />
					<main
						className='p-8 flex-1'
						data-testid='main-content'>
						{children}
					</main>
					<Footer />
				</body>
			</html>
		</Providers>
	);
}
