import '@/app/globals.css';
import { RootLayoutContent } from '@/components/layout/RootLayoutContent';
import { Analytics } from '@vercel/analytics/next';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <RootLayoutContent>{children}</RootLayoutContent>
                <Analytics />
            </body>
        </html>
    );
}
